#############################################################################
# Makefile for building: Delaunay_triangulation
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? ??? 30 22:21:35 2017
# Project:  Delaunay_triangulation.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Delaunay_triangulation.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = canvas.cpp \
		delaunay_algo.cpp \
		edge.cpp \
		main.cpp \
		node.cpp \
		point.cpp \
		polygon.cpp \
		tree_node.cpp moc_canvas.cpp
OBJECTS       = canvas.o \
		delaunay_algo.o \
		edge.o \
		main.o \
		node.o \
		point.o \
		polygon.o \
		tree_node.o \
		moc_canvas.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Delaunay_triangulation.pro
QMAKE_TARGET  = Delaunay_triangulation
DESTDIR       = 
TARGET        = Delaunay_triangulation

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_canvas.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Delaunay_triangulation.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Delaunay_triangulation.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Delaunay_triangulation.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Delaunay_triangulation1.0.0 || $(MKDIR) .tmp/Delaunay_triangulation1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Delaunay_triangulation1.0.0/ && $(COPY_FILE) --parents braided_node.h canvas.h delaunay_algo.h edge.h node.h point.h polygon.h randomized_node.h tree_node.h .tmp/Delaunay_triangulation1.0.0/ && $(COPY_FILE) --parents canvas.cpp delaunay_algo.cpp edge.cpp main.cpp node.cpp point.cpp polygon.cpp tree_node.cpp .tmp/Delaunay_triangulation1.0.0/ && $(COPY_FILE) --parents canvas.ui .tmp/Delaunay_triangulation1.0.0/ && (cd `dirname .tmp/Delaunay_triangulation1.0.0` && $(TAR) Delaunay_triangulation1.0.0.tar Delaunay_triangulation1.0.0 && $(COMPRESS) Delaunay_triangulation1.0.0.tar) && $(MOVE) `dirname .tmp/Delaunay_triangulation1.0.0`/Delaunay_triangulation1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Delaunay_triangulation1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_canvas.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_canvas.cpp
moc_canvas.cpp: delaunay_algo.h \
		randomized_node.h \
		braided_node.h \
		tree_node.h \
		node.h \
		edge.h \
		point.h \
		polygon.h \
		canvas.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) canvas.h -o moc_canvas.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_canvas.h
compiler_uic_clean:
	-$(DEL_FILE) ui_canvas.h
ui_canvas.h: canvas.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic canvas.ui -o ui_canvas.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

canvas.o: canvas.cpp canvas.h \
		delaunay_algo.h \
		randomized_node.h \
		braided_node.h \
		tree_node.h \
		node.h \
		edge.h \
		point.h \
		polygon.h \
		ui_canvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canvas.o canvas.cpp

delaunay_algo.o: delaunay_algo.cpp delaunay_algo.h \
		randomized_node.h \
		braided_node.h \
		tree_node.h \
		node.h \
		edge.h \
		point.h \
		polygon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delaunay_algo.o delaunay_algo.cpp

edge.o: edge.cpp edge.h \
		point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o edge.cpp

main.o: main.cpp canvas.h \
		delaunay_algo.h \
		randomized_node.h \
		braided_node.h \
		tree_node.h \
		node.h \
		edge.h \
		point.h \
		polygon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

node.o: node.cpp node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o node.cpp

point.o: point.cpp point.h \
		edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point.o point.cpp

polygon.o: polygon.cpp polygon.h \
		node.h \
		point.h \
		edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o polygon.o polygon.cpp

tree_node.o: tree_node.cpp tree_node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tree_node.o tree_node.cpp

moc_canvas.o: moc_canvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_canvas.o moc_canvas.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

